# Generated by Django 4.1.6 on 2023-03-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfo",
            old_name="portfolio",
            new_name="portfolio_site",
        ),
        migrations.RenameField(
            model_name="userprofileinfo",
            old_name="picture",
            new_name="profile_pic",
        ),
    ]
